[package]
type = 'bash'
name = 'bash-runtime-hyperupcall'
slug = 'hyperupcall'
version = '0.0.0'
authors = ['Edwin Kofler edwin@kofler.dev']
description = 'TEMPLATE_DESCRIPTION'

[run]
dependencies = []
binDirs = []
sourceDirs = ['pkg/src/public']
builtinDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]
errexit = 'on'
pipefail = 'on'

[run.shoptOptions]
nullglob = 'on'
shift_verbose = 'on'
